### ISSUE TITLE
visualpriors source code

### ISSUE THREAD

**Issue by huiwenzhang** [alexsax/midlevel-reps#1]
Hi, 
Thanks for providing this tool. I want to use the visualpriors in my project. And I am considering maybe I can extend the visualpriors by including new features. However, I can't find the  source code for this package. The only repository I found is: https://github.com/alexsax/visual-prior. But only checkpoint files are included. Is it redirected to somewhere else?
Thanks

**Comment by alexsax** [comment]
Hi, 
https://github.com/alexsax/visual-prior is indeed the correct repository. Right now there are two branches: `master` (with source code) and `networks` with checkpoints. I just switched the default branch back to `master` so hopefully the source code should now be easier to find.

Let me know if this link isn't what you want: https://github.com/alexsax/visual-prior/tree/master

Thanks for reaching out!
