### ISSUE TITLE
Variable not defined

### ISSUE THREAD

**Issue by paeccher** [alexsax/midlevel-reps#10]
Hello, I was trying and inspecting the code of visualpriors and I think that in the `max_coverage_featureset_transform` function you forgot to change the name of the second parameter that is passed to the function at line 45. In fact, `feature_tasks`, is not defined and I think that you meant to pass `k` instead. 

https://github.com/alexsax/midlevel-reps/blob/4f3ac49e5e5540b7534ab658cef415c67f3cad28/visualpriors/transforms.py#L29-L45

**Comment by alexsax** [comment]
Thanks for this catch! I just pushed a new version with your change. 

You can get the latest version with `pip install --upgrade visualpriors`
