### ISSUE TITLE
Feature readout does not work with semantic networks

### ISSUE THREAD

**Issue by smorad** [alexsax/midlevel-reps#6]
I get the following images when running `feature_readout`

Input image:
![lbkedkoomddhdkca](https://user-images.githubusercontent.com/1743889/73262725-cef95c00-41c6-11ea-8dbc-ca41846a4e66.png)
Normals:
![dohhdobhmhdbgdmp](https://user-images.githubusercontent.com/1743889/73262726-cef95c00-41c6-11ea-9233-bae11d3d8a57.png)
Segment unsup2D
![pcogflojfgahakel](https://user-images.githubusercontent.com/1743889/73262728-cef95c00-41c6-11ea-9111-692fecb61f2b.png)
Semantic segment
![fapmfljjjjaghone](https://user-images.githubusercontent.com/1743889/73262729-cf91f280-41c6-11ea-9fc5-b4bc68d6f064.png)
Segment unsup25D
![boaokcjkoabfchci](https://user-images.githubusercontent.com/1743889/73262730-cf91f280-41c6-11ea-979b-490bc896ebc3.png)

Does anything special need to be done to render the semantic representations?

**Comment by smorad** [comment]
Figured this out, the semantic segment outputs a channel for each label. By taking the argmax over all channels, you can find the maximum likelihood label for any specific pixel. Then just map each pixel to the RGB value corresponding to the argmax.

**Comment by GELIELEO** [comment]
can you provide any code to solve it, thank you very much. @smorad

**Comment by smorad** [comment]
Something similar to this
```
rgb_map = [[random.random() for j in range(3)] for i in range(100)]
_, argmax = np.max(img, dim=1)
for pixel_i in image:
   new_img[pixel_i] = rgb_map[argmax]
```
