### ISSUE TITLE
screen command failed "No screen session found."

### ISSUE THREAD

**Issue by WSPeng** [alexsax/midlevel-reps#8]
Hi,
In the step 3 (Start visualization services) in Experiments in Habitat: $screen -S visdom_server -p 0 -X stuff "visdom^M"
Error message "No screen session found" is returned. 
May I ask how to work around this problem?
Thank you

**Comment by alexsax** [comment]
The only point of this command is to start a visdom server on your local machine. The visdom server is there so that you can view the logged results. You could use any method for starting that server in the background:, `screen`, `tmux`, `nohup`, etc--whatever you usually prefer should work here.

**Comment by liuqi8827** [comment]
@WSPeng @alexsax 
Hi, I'm facing the same problem.
In the step 3 (Start visualization services) in Experiments in Habitat: $screen -S visdom_server -p 0 -X stuff "visdom^M"
Error message "No screen session found" is returned.

Did you solved this problem？
Thanks!
