### ISSUE TITLE
Pretrained checkpoint

### ISSUE THREAD

**Issue by jeffjunzhang** [alexsax/midlevel-reps#9]
Hi,

In the paper, it mentions the pre-trained models are available.

I'm wondering where we can find the pre-trained checkpoints for the agents, such as "Max-Coverage Min-Distance Featureset?"

**Comment by alexsax** [comment]
We're still working on publicly hosting all of the policy checkpoints. However, fear not.

The networks used to get the mid-level representations are available (see the README, and specifically the section [Using Mid-Level Perception in Your code](https://github.com/alexsax/midlevel-reps#using-mid-level-perception-in-your-code-)).

There's also a section in the README on how to run some of our experiments--you could use that to train a new policy using either our setup or your own.
